name: Build Docker Image

on:
- push

env:
  DOCKERHUB_USER: "${{ secrets.DOCKERHUB_USER }}"
  DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
        - "4"
    steps:
    - uses: actions/checkout@v1
    - name: Build the image.
      id: build
      run: |
        printf "::group::Sending context\n"
        IMAGE=adminer:4.8.1-oracle_x64
        docker build "$VARIANT" --tag "$IMAGE" |sed 's/^Step/::endgroup::\n::group::Step/'
        printf "::endgroup::\n"
        printf "::set-output name=%s::%s\n" "image" "$IMAGE"
        printf "::set-output name=%s::%s\n" "version" "$(awk '/^ENV\s+ADMINER_VERSION/{print $3}' "$VARIANT/Dockerfile")"
      env:
        VARIANT: ${{ matrix.variant }}
    - name: Show Containers and Images
      run: |
        printf "::group::docker ps -a\n"
        docker ps -a
        printf "::endgroup::\n"
        printf "::group::docker images\n"
        docker images
        printf "::endgroup::\n"
        printf "::group::docker login\n"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        printf "::endgroup::\n"
        printf "::group::docker tag\n"
        docker tag adminer:4.8.1-oracle_x64 xijiahui/adminer:4.8.1-oracle_x64
        printf "::endgroup::\n"
        printf "::group::docker push\n"
        docker push xijiahui/adminer:4.8.1-oracle_x64
        printf "::endgroup::\n"
